data/npc/scripts/Hairycles.lua

Added function msgcontains of player say cookie for "What a Foolish Quest" at NPC Hairycles.

Add function msgcontains (cookie)

---

data/actions/scripts/quests/what a foolish/worncloth.lua

Mission 11 What a Foolish Quest

BUG FIX Bale of White Cloth

---

data/npc/scripts/Bozo.lua

Fixed Dialog of Bozo.
Credits: GOD Bon [Johnny Eugênio]

FIXED Dialog of Bozo

---

data/actions/scripts/quests/what a foolish/disguise.lua

Item Disappear when used like in Tibia RL.

Item Disappear when used like in Tibia RL

---

data/actions/lib/actions.lua

Remove chest and add fix lava hole using action id: 14031

What Foolish Quest Mission 8 add Lava hole

---

data/actions/scripts/other/uniwheel.lua

Added Chance break item, added storage player for use golden can of oil one times after taming and message equals tibia real.

UPDATE UNIWHEEL TAMING SCRIPT

---

data/lib/miscellaneous/051-storages.lua

ADDED Uniwheel Storage

---

data/spells/scripts/support/haste.lua

Fixed the magic spell haste that does not remove the paralyze.

Fixed haste.lua

---

data/spells/scripts/support/strong haste.lua

Fixed the magic spell strong haste that does not remove the paralyze.

Fixed strong haste.lua

---

data/spells/scripts/attack/annihilation.lua

UPDATE DAMAGE EXORI GRAN ICO

---

data/spells/scripts/attack/strong ethereal spear.lua

UPDATE EXORI GRAN CON DAMAGE

---

data/spells/scripts/attack/fierce berserk.lua

UPDATE FORMULA EXORI GRAN FOR MORE DAMAGE!

UPDATE FORMULA EXORI GRAN

---

data/spells/scripts/attack/berserk.lua

UPDATE FORMULA EXORI! MORE DAMAGE EQUALS TIBIA RL

UPDATE FORMULA EXORI

---

data/actions/scripts/quests/demon oak/demonOak.lua

Changes demon oak monsters to reflect RL Tibia  http://tibia.wikia.com/wiki/The_Demon_Oak_Quest/Spoiler

Fixing demon oak monsters like RL tibia

---

data/actions/scripts/other/potions.lua
data/actions/scripts/quests/demon oak/demonOak.lua

Fixed potions to get the empty flask to be able to do the belt addon like RL tibia http://tibia.wikia.com/wiki/Summoner_Outfits_Quest/Spoiler

Fix potions

---

data/items/items.xml
data/spells/lib/spells.lua

Updated as many of the 10.94 weapons (carving, mayhem, remedy) that I could find. Re organized the list so when you use "/i rod of mayhem" you get the item that is brand new and not on a timer.

update 10.94 weapons

---

data/items/items.xml

Fixed the attributes and ordering for collar and ring of red/green/blue
plasma. Also fixed the names. Fixed soft boots to have the proper
regeneration rates from wiki.

collar/ring of red/green/blue plasma, sb fix

---

data/talkactions/scripts/buyhouse.lua

Adjusted script to buy the house with gold from bank account, since this
is how it works in real tibia. Also adjusted the messaging to include
price and frequency of rent so the player knows.

Buy house with bank gold (like real tibia), update buy message

---

data/npc/scripts/Ajax.lua
data/npc/scripts/Bron.lua

REF: http://tibia.wikia.com/wiki/Barbarian_Outfits_Quest/Spoiler

Fix barbarianoutfit

---

data/actions/scripts/other/music.lua

- Added the possibility of completing the diapason quest by playing lyre to Edala every 24hs (http://tibia.wikia.com/wiki/Diapason)
- Added progress towards the rockstar achievement when playing instruments (http://tibia.wikia.com/wiki/Rockstar).

Fixed music.lua

---

data/actions/lib/actions.lua

Fixed behavior to cut sugar cane according to http://tibia.wikia.com/wiki/Bunch_of_Sugar_Cane
Behavior can be seen here: https://www.youtube.com/watch?v=QZE4u5ed1qQ at 1:20

Fixed sugar cane

---

data/actions/scripts/other/baking.lua

Fixed creating sugar oat according to: http://tibia.wikia.com/wiki/Sugar_Oat
Behavior can be seen here: https://www.youtube.com/watch?v=QZE4u5ed1qQ at 2:50

Fixed creating sugaroat

---

data/actions/actions.xml
data/actions/scripts/other/tibiacoins.lua
data/items/items.xml
src/iologindata.cpp
src/luascript.cpp
src/luascript.h
src/player.cpp
src/player.h

Added tibiacoins lua functions to source codes, added action to give 250
coins when using premium scroll (like real tibia), fixed name of premium
scroll in items.xml. Also players can right click tibia coins to add
them to their balance.

TibiaCoins

---

data/npc/Rock In A Hard Place.xml

REF: http://tibia.wikia.com/wiki/Rock_In_A_Hard_Place

Added missing empty flasks

---

data/npc/Rabaz.xml

Added missing empty potion flasks according to: http://tibia.wikia.com/wiki/Rabaz

Fixed NPC Rabaz

---

data/npc/scripts/Hjaern.lua
data/npc/scripts/Walter, The Guard.lua

Fixed missing keyword for Walter
Fixed typo in Hjaern

Fixed Hjaern and Walter

---

data/actions/scripts/other/carpets.lua
data/items/items.xml

Items - Carpets

---

data/actions/actions.xml

Missing action for BK quest

---

config.lua
data/actions/scripts/other/potions.lua
src/configmanager.cpp
src/configmanager.h

Flag to disable Potion charge consumption

Flag to disable Potion charge consumption

---

data/creaturescripts/scripts/gaz'haragoth heal.lua

Fix amount and time of heal based on http://tibia.wikia.com/wiki/Gaz%27haragoth

Fixed Heal

---

data/monster/bosses/gaz'haragoth.xml

Fixed attacks, def, spells
Fixed Death and Doom, Heal.
Based on http://tibia.wikia.com/wiki/Gaz%27haragoth

Fixed Gaz'Haragoth

---

data/creaturescripts/creaturescripts.xml
data/creaturescripts/scripts/others/impact_analyzer.lua
data/global.lua
data/lib/core/player.lua

Initial implementation of impact analyzer graph. We need to test if it breaks clients older than 11.34 aswell as legacy 10 client
Implementação inicial do gráfico do impact analyzer. A gente precisa testar se isso quebra clientes anteriores ao 11.34 ou o 10 legado.

[WIP] Impact Analyzer

---

data/monster/bosses/countess_sorrow.xml
data/monster/bosses/dracola.xml
data/monster/bosses/massacre.xml
data/monster/bosses/mr. punish.xml
data/monster/bosses/mr._punish.xml
data/monster/bosses/the handmaiden.xml

Fix POI bosses loot

---

data/actions/actions.xml

Add new Carpets and fix Carperts

Add new Carpets and fix Carperts

---

data/creaturescripts/creaturescripts.xml
data/creaturescripts/scripts/others/login.lua
data/creaturescripts/scripts/pet.lua
data/spells/scripts/support/pet.lua
data/spells/spells.xml

- New Summons (Pets) Relogin with Time Spell
- Buffer in Spell Pets (set storage osTime())
- Now Pets Remove with Onthink with Storage

New Summons (Pets) Relogin with Time Spell

---

data/spells/scripts/support/pet.lua

Definitive Fixed Spell Pet

---

data/monster/monsters.xml

add the keeper

---

data/npc/scripts/Alesar.lua
data/npc/scripts/Angus.lua
data/npc/scripts/Haroun.lua
data/npc/scripts/Melchior.lua
data/npc/scripts/Nah'Bob.lua
data/npc/scripts/Rashid.lua
data/npc/scripts/Yaman.lua
data/raids/raids.xml
data/raids/rookgaard/munster.xml
data/raids/rookgaard/rats.xml
data/raids/rookgaard/rottie1.xml
data/raids/rookgaard/rottie2.xml
data/raids/rookgaard/sheng.xml
data/raids/rookgaard/teleskor.xml

Djinns
- 'The Djinn War Quest' is now needed to trade with adequate Djinns (however now it's disabled - need to delete script blockade)
- small tweak in Melchior's script
Rashid
- 'The Travelling Trader Quest' is now needed to trade with Rashid (disabled like in Djinns' script)
- real towns' names
Rookgaard
- added rook-boss raids

Djinns and Rashid trading; Rookgaard bosses

---

data/monster/Bosses/koshei_the_deathless.xml
data/npc/Azil.xml

- Azil - buy/sell items update
- Koshei the Deathless fix - wrong corpse ID so the amulet didn't work

NPC Azil & Koshei fix

---

data/npc/scripts/Karith.lua

Fix to NPC Karith script (problem with storage value)

NPC Karith (fix to #693)

---

data/actions/scripts/addons/afflictedoutfit.lua

Fix for using plague mask/bell to obtain addon (Issue https://github.com/malucooo/Otxserver-New/issues/704)

Afflicted outfit - addon fix

---

data/items/items.xml
data/monster/monsters.xml
data/npc/Hairycles.xml
data/npc/scripts/Albinius.lua
data/npc/scripts/Briasol.lua
data/npc/scripts/Captain Waverider.lua
data/npc/scripts/Hairycles.lua
data/npc/scripts/Rashid.lua
data/npc/scripts/The Blind Prophet.lua
data/npc/scripts/Uzon.lua
data/raids/libertybay/crustacea_gigantica1.xml
data/raids/libertybay/crustacea_gigantica2.xml
data/raids/libertybay/crustacea_gigantica3.xml
data/raids/oramond/crustacea_gigantica4.xml
data/raids/oramond/crustacea_gigantica5.xml
data/raids/raids.xml

NPCs
- Albinius - typo
- Uzon - typo
- The Blind Prophet - small fix
- Briasol and Rashid - itemID fix for 'fine vase' (Travelling Trader Quest)
- Captain Waverider - don't need gold in inventory to pay for passage
- Hairycles - now he sells monkey statuettes, but only after completing 'The Ape City Quest'
Monsters
- Orc with Sam's backpack added to monsters.xml
- added 5 raid-spawns of Crustacea Gigantica (under Treasure Island, 2x Calassa, 2x Seacrest Grounds)
- removed 'normal' spawn of Crustacea Gigantica
Items
- 'Heavy Old Tome' weight fix

Bunch of fixes

---

data/actions/scripts/quests/dreamer challenge/stoneTeleport.lua

Dreamer's Challenge Quest fix (Issue #711)

---

data/npc/scripts/Lurik.lua

Fix for #764

---

data/actions/actions.xml
data/actions/scripts/farmine/elevatorLever.lua
data/actions/scripts/quests/the new frontier/lever.lua
data/monster/Glires/enraged squirrel.xml
data/monster/Glires/thieving squirrel.xml
data/monster/monsters.xml
data/npc/scripts/Brodrosch.lua
data/npc/scripts/Gurbasch.lua
data/npc/scripts/Leeland.lua

- fixed all levers (propably it's also fix to #697) - now they TP you to adequate position according to present Farmine stage, but:
-- lever on (x=33061, y=31527, z=12) need to have actionID 9122
-- lever on (x=33061, y=31527, z=14) need to have actionID 9123
-- I asked @igordelecrode to do that changes so I believe it would be fixed in upcoming map update
- NPC Brodrosch and Gurbasch now carry you to proper position (according to present Farmine stage)
- Mission 2 - added enraged and thieving squirrels because they were not spawned while mission
- Mission 5 - Leeland small fix, nothing important

The New Frontier Quest - fixes

---

data/npc/scripts/Jack Fate.lua
data/npc/scripts/Jack FateGoroma.lua

Part of The Shattered Isles Quest

Fixed Access to Goroma
